import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    return [
      {
        image: "assets/images/uy-flag.png",
        title: "UY Best country ever",
        subtitle: "nice place",
        content: "This message is autogenerated"
      },
      {
        image: "assets/images/uy-ball.png",
        title: "UY",
        subtitle: "Montevideo",
        content: "Aloha"
      },
      {
        image: "assets/images/lab.png",
        title: "Lab time",
        subtitle: "Chemistry is awsome",
        content: "bla bla"
      }
    ];
  }
});
